# Minecraft Server Properties - Optimized for Low RAM Cloud Hosting
server-port=25565
view-distance=4
simulation-distance=4
max-players=10
gamemode=survival
difficulty=easy
online-mode=true
enable-command-block=true
spawn-protection=0
motd=A 24/7 Cloud Minecraft Server
network-compression-threshold=256
sync-chunk-writes=false
enable-query=false
enable-rcon=false
entity-broadcast-range-percentage=50
max-world-size=29999984
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
pvp=true
allow-flight=true
level-name=world
